name: TBS build

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build Image
      id: build
      uses: vmware-tanzu/build-image-action@v1-alpha
      with:
        # Authorization
        server: ${{ secrets.SERVER }}
        token: ${{ secrets.TOKEN }}
        ca_cert: ${{ secrets.CA_CERT }}
        namespace: dev
        # Image configuration
        destination: supply-chain/tanzu-java-web-app-default-bundle/workloads/spring-boot-hello-world
    - name: Do something with image
      run:
        echo "${{ steps.build.outputs.name }}"